/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication10;

/**
 *
 * @author sena
 */
public class maquina extends javax.swing.JFrame {
    boolean estado = true;

    /**
     * Creates new form maquina
     */
    public maquina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resultado_compra = new javax.swing.JButton();
        producto1 = new javax.swing.JCheckBox();
        producto2 = new javax.swing.JCheckBox();
        producto3 = new javax.swing.JCheckBox();
        producto4 = new javax.swing.JCheckBox();
        producto5 = new javax.swing.JCheckBox();
        producto6 = new javax.swing.JCheckBox();
        producto7 = new javax.swing.JCheckBox();
        producto8 = new javax.swing.JCheckBox();
        producto9 = new javax.swing.JCheckBox();
        producto10 = new javax.swing.JCheckBox();
        producto11 = new javax.swing.JCheckBox();
        producto12 = new javax.swing.JCheckBox();
        producto13 = new javax.swing.JCheckBox();
        producto14 = new javax.swing.JCheckBox();
        producto15 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dinero = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        numero1 = new javax.swing.JButton();
        numero2 = new javax.swing.JButton();
        numero3 = new javax.swing.JButton();
        numero4 = new javax.swing.JButton();
        numero5 = new javax.swing.JButton();
        numero6 = new javax.swing.JButton();
        numero7 = new javax.swing.JButton();
        numero8 = new javax.swing.JButton();
        numero9 = new javax.swing.JButton();
        numero0 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("TlwgTypewriter", 2, 18)); // NOI18N
        jLabel2.setText("seleccione los dulces que desee comprar");

        resultado_compra.setFont(new java.awt.Font("TlwgTypewriter", 2, 24)); // NOI18N
        resultado_compra.setText("comprar duclces");
        resultado_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultado_compraActionPerformed(evt);
            }
        });

        producto1.setText("A01 $800");

        producto2.setText("A02  $900");

        producto3.setText("A03  $900");

        producto4.setText("A04 $1500");
        producto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto4ActionPerformed(evt);
            }
        });

        producto5.setText("A05 $700");
        producto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto5ActionPerformed(evt);
            }
        });

        producto6.setText("B01 $1100");

        producto7.setText("B02 $1300");

        producto8.setText("B03 $1800");

        producto9.setText("B04 $700");

        producto10.setText("B05 $1500");

        producto11.setText("C01 $800");

        producto12.setText("C02 $800");

        producto13.setText("C03 $1200");
        producto13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto13ActionPerformed(evt);
            }
        });

        producto14.setText("C04 $800");

        producto15.setText("C05  $1100");

        jLabel3.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel3.setText("chcolatina jet");

        jLabel4.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel4.setText("minichips");

        jLabel5.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel5.setText("galleta festival");

        jLabel6.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel6.setText("platanitos");

        jLabel7.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel7.setText("burbuja jet");

        jLabel8.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel8.setText("manimoto");

        jLabel9.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel9.setText("pastelito ramo");

        jLabel10.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel10.setText("     m&m");

        jLabel11.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel11.setText("galleta oreo");

        jLabel12.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel12.setText("Mlikyway");

        jLabel13.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel13.setText("boliqueso");

        jLabel14.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel14.setText("galleta club social");

        jLabel15.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel15.setText("maicitos");

        jLabel16.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel16.setText("chockis");

        jLabel17.setFont(new java.awt.Font("TlwgTypewriter", 2, 14)); // NOI18N
        jLabel17.setText("barra de halls");

        dinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dineroActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("TlwgTypewriter", 2, 18)); // NOI18N
        jLabel18.setText("Ingrese la cantidad de dinero correspondiente");

        numero1.setText("1");
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });

        numero2.setText("2");
        numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero2ActionPerformed(evt);
            }
        });

        numero3.setText("3");
        numero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero3ActionPerformed(evt);
            }
        });

        numero4.setText("4");
        numero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero4ActionPerformed(evt);
            }
        });

        numero5.setText("5");
        numero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero5ActionPerformed(evt);
            }
        });

        numero6.setText("6");
        numero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero6ActionPerformed(evt);
            }
        });

        numero7.setText("7");
        numero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero7ActionPerformed(evt);
            }
        });

        numero8.setText("8");
        numero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero8ActionPerformed(evt);
            }
        });

        numero9.setText("9");
        numero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero9ActionPerformed(evt);
            }
        });

        numero0.setText("0");
        numero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(producto15)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(producto6)
                                                        .addGap(23, 23, 23))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel8)
                                                            .addComponent(jLabel3)
                                                            .addComponent(producto11)
                                                            .addComponent(producto1))
                                                        .addGap(12, 12, 12)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(20, 20, 20)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(producto7)
                                                            .addComponent(jLabel9)
                                                            .addComponent(producto2)
                                                            .addComponent(jLabel4)))
                                                    .addComponent(jLabel14)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(16, 16, 16)
                                                        .addComponent(producto12)))
                                                .addGap(49, 49, 49)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addComponent(producto3))
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel5)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(producto8)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel13)
                                                    .addGap(263, 263, 263)
                                                    .addComponent(producto13))))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(producto4))
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel16)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(producto9)
                                                .addComponent(jLabel11)
                                                .addComponent(producto14))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(23, 23, 23)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel12)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(producto10))))
                            .addComponent(producto5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultado_compra)
                .addGap(335, 335, 335))
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero1)
                    .addComponent(numero4)
                    .addComponent(numero7))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero0)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numero2)
                            .addComponent(numero5)
                            .addComponent(numero8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numero9)
                            .addComponent(numero6)
                            .addComponent(numero3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero1)
                            .addComponent(numero3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero4)
                            .addComponent(numero6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero7)
                            .addComponent(numero9)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numero2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numero0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(producto2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel9)
                            .addGap(17, 17, 17)
                            .addComponent(producto7)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel14))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(12, 12, 12)
                            .addComponent(producto1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8)
                            .addGap(17, 17, 17)
                            .addComponent(producto6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel13)
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(producto11)
                                        .addComponent(producto12)
                                        .addComponent(producto13)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel15)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(producto5)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(producto10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addGap(48, 48, 48))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(producto3)
                                    .addComponent(producto4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(producto8)
                                    .addComponent(producto9))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(producto14)
                                    .addComponent(producto15))))
                        .addGap(6, 6, 6)))
                .addGap(30, 30, 30)
                .addComponent(resultado_compra)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultado_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultado_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultado_compraActionPerformed

    private void producto13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producto13ActionPerformed

    private void producto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producto4ActionPerformed

    private void producto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producto5ActionPerformed

    private void dineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dineroActionPerformed

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
  
        String num1=numero1.getText();
        int nnumero1 = Integer.parseInt(num1);
        
         if (estado){
     num1=num1+1;
     dinero.setText(dinero.getText()+numero1.getText());         
 } 
 else{
             
      System.out.println(num1);  
                   
 }
        
        
    
    }//GEN-LAST:event_numero1ActionPerformed

    private void numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero2ActionPerformed
      String num2=numero2.getText();
        int nnumero2 = Integer.parseInt(num2); 
         if (estado){
     num2=num2+2;
    dinero.setText(dinero.getText()+numero2.getText());  
         }else
         {

         }
    }//GEN-LAST:event_numero2ActionPerformed

    private void numero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero3ActionPerformed
         String num3=numero3.getText();
        int nnumero3 = Integer.parseInt(num3); 
         if (estado){
     num3=num3+3;
    dinero.setText(dinero.getText()+numero3.getText());  
         }else
         {

         }
    }//GEN-LAST:event_numero3ActionPerformed

    private void numero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero4ActionPerformed
         String num4=numero4.getText();
        int nnumero4 = Integer.parseInt(num4); 
         if (estado){
     num4=num4+4;
    dinero.setText(dinero.getText()+numero4.getText());  
         }else
         {

         }
    }//GEN-LAST:event_numero4ActionPerformed

    private void numero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero5ActionPerformed
          String num5=numero5.getText();
        int nnumero5 = Integer.parseInt(num5); 
         if (estado){
     num5=num5+5;
    dinero.setText(dinero.getText()+numero5.getText());  
         }else
         {

         }
    }//GEN-LAST:event_numero5ActionPerformed

    private void numero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero6ActionPerformed
          String num6=numero6.getText();
        int nnumero6 = Integer.parseInt(num6); 
         if (estado){
     num6=num6+6;
    dinero.setText(dinero.getText()+numero6.getText());  
         }else
         {

         }
    }//GEN-LAST:event_numero6ActionPerformed

    private void numero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero7ActionPerformed
          String num7=numero7.getText();
        int nnumero7 = Integer.parseInt(num7); 
         if (estado){
     num7=num7+7;
    dinero.setText(dinero.getText()+numero7.getText());  
         }else
         {

         }
    }//GEN-LAST:event_numero7ActionPerformed

    private void numero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero8ActionPerformed
          String num8=numero8.getText();
        int nnumero8 = Integer.parseInt(num8); 
         if (estado){
     num8=num8+8;
    dinero.setText(dinero.getText()+numero8.getText());  
         }else
         {

         }
    }//GEN-LAST:event_numero8ActionPerformed

    private void numero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero9ActionPerformed
          String num9=numero9.getText();
        int nnumero9 = Integer.parseInt(num9); 
         if (estado){
     num9=num9+9;
    dinero.setText(dinero.getText()+numero9.getText());  
         }else
         {

         }
    }//GEN-LAST:event_numero9ActionPerformed

    private void numero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero0ActionPerformed
          String num0=numero0.getText();
        int nnumero2 = Integer.parseInt(num0); 
         if (estado){
     num0=num0+0;
    dinero.setText(dinero.getText()+numero0.getText());  
         }else
         {

         }
    }//GEN-LAST:event_numero0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new maquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dinero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton numero0;
    private javax.swing.JButton numero1;
    private javax.swing.JButton numero2;
    private javax.swing.JButton numero3;
    private javax.swing.JButton numero4;
    private javax.swing.JButton numero5;
    private javax.swing.JButton numero6;
    private javax.swing.JButton numero7;
    private javax.swing.JButton numero8;
    private javax.swing.JButton numero9;
    private javax.swing.JCheckBox producto1;
    private javax.swing.JCheckBox producto10;
    private javax.swing.JCheckBox producto11;
    private javax.swing.JCheckBox producto12;
    private javax.swing.JCheckBox producto13;
    private javax.swing.JCheckBox producto14;
    private javax.swing.JCheckBox producto15;
    private javax.swing.JCheckBox producto2;
    private javax.swing.JCheckBox producto3;
    private javax.swing.JCheckBox producto4;
    private javax.swing.JCheckBox producto5;
    private javax.swing.JCheckBox producto6;
    private javax.swing.JCheckBox producto7;
    private javax.swing.JCheckBox producto8;
    private javax.swing.JCheckBox producto9;
    private javax.swing.JButton resultado_compra;
    // End of variables declaration//GEN-END:variables
}
